//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muestras
    {
        public int Id { get; set; }
        public string Persona_Muestrada { get; set; }
        public Nullable<System.DateTime> Fecha_Toma { get; set; }
        public string Persona_Toma_Muestra { get; set; }
    }
}
